package interface_adapter.generated_recipes;

import java.util.ArrayList;

import entity.Recipe;

/**
 * Represents the state of generated recipes in the application.
 * This class is responsible for managing the list of recipes generated
 * by the recipe recommendation system.
 */
public class GeneratedState {

    /**
     * Updates the state with the provided list of generated recipes.
     *
     * @param generatedRecipes The list of recipes generated by the system.
     */
    public void setGeneratedRecipes(ArrayList<Recipe> generatedRecipes) {
    }

}
